version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"


volumes:
  postgres_data:
